### ISSUE TITLE
重复文件都在mainfolder的问题

### ISSUE THREAD

**Issue by shgzb99** [tobyqin/photodup#4]
用auto.py删除重复文件，如果刚好文件都在mainfolder,会把mainfolder里的重复文件都删除，文件就丢失了。
比如，A和B两个文件重复，且都在mainfolder里，用auto.py扫描时，会将AB两个文件都删除。

**Comment by tobyqin** [comment]
这种情况auto模式是没办法智能处理的，因为我也不知道你要保留哪个版本，这种情况最好是通过网页端手动选择。

如果AB不在同一文件夹，那么用auto会方便很大。

我的流程大概是这样，先auto清理一大部分，然后网页点一点就搞定了。
